### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by anfly0** [MindscapeHQ/raygun4php#115]
Does anyone know if there is any official or reasonably correct JSON schema available for the /entries endpoint?

I'm currently looking at moving some methods from the RaygunClient class to the RaygunMessage class, and it would be great to have a schema to check the serialized message objects aginst.

The main problem I'm having is the [documentation](https://raygun.com/documentation/product-guides/crash-reporting/api/)  is not very clear on what fields are mandatory.

**Comment by BenjaminHarding** [comment]
Sorry for the delayed reply @anfly0. 

This is a bit tricky to answer, because different fields are "required" for different things. The fields that are absolutely required is `occurredOn` and `details` - this will allow the api to accept it but they won't be that useful. It's likely that we'll want error => className, message, stackTrace => className, methodName to get the minimum useful information. 

Additional fields are then added depending on what else is needed or found useful when debugging issues. 

Hope that clears some stuff up?
