### ISSUE TITLE
Optionally do not send server variables

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4php#73]
We want to be able to configure our PHP Raygun client to not include server variables when sending reports. The reason is that a lot of environment variables can contain confidential data and filtering it out with regular expressions is just a maintenance hassle.

From here: https://raygun.io/thinktank/suggestion/28144

**Comment by davesouthey** [comment]
Is there an update on this? I also would find this enhancement helpful.

**Comment by fundead** [comment]
This is still scheduled on the backlog but this provider isn't immediately scheduled for a refresh due to other work in the pipeline. In the meantime you can use the Filtering feature at https://github.com/MindscapeHQ/raygun4php#filtering-sensitive-data. I will look at resolving this issue for you when next possible.

**Comment by GuySartorelli** [comment]
Is the intention to indiscriminately filter out ALL server variables, or to filter out specific variables? The latter is already implemented so if that's the case this should be closed.
If the intention was for the former, I'm happy to raise a PR so we can get this closed out.

**Comment by sumitramanga** [comment]
Hi there, I'll be closing this out as this is now a stale Issue.

If anyone is keeping an eye on this Issue, we are happy to re open and discuss if more help us required! Just let us know :) 

Cheers,
Sumitra
